"""empty message

Revision ID: 68afc4d4ce66
Revises: 3a34a50f7822
Create Date: 2024-01-21 16:19:54.850958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68afc4d4ce66'
down_revision = '3a34a50f7822'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_username', ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_username', type_='unique')

    # ### end Alembic commands ###
