"""empty message

Revision ID: 744e06a06dd0
Revises: af4a5666c84f
Create Date: 2024-01-19 12:23:02.394427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '744e06a06dd0'
down_revision = 'af4a5666c84f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_confirmed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('email_confirmed')

    # ### end Alembic commands ###
